<h4>Bow-Bag of Words</h4>

In [29]:
import pandas as pd
import numpy as np

In [30]:
text={"text":["People watch Aiyug","Aiyug watch Aiyug","People write comment","Aiyug write comment"],"Output":[1,1,0,0]}

In [31]:
text=pd.DataFrame(text)

In [32]:
text

,text,Output
0,People watch Aiyug,1
1,Aiyug watch Aiyug,1
2,People write comment,0
3,Aiyug write comment,0


In [33]:
from sklearn.feature_extraction.text import CountVectorizer

In [34]:
cv=CountVectorizer(lowercase=True,stop_words='english',binary=True)

In [35]:
bow=cv.fit_transform(text['text'])

In [36]:
cv.vocabulary_

{'people': 2, 'watch': 3, 'aiyug': 0, 'write': 4, 'comment': 1}

In [37]:
print(bow[0].toarray())
print(bow[1].toarray())
print(bow[2].toarray())     
print(bow[3].toarray())

[[1 0 1 1 0]]
[[1 0 0 1 0]]
[[0 1 1 0 1]]
[[1 1 0 0 1]]


In [38]:
cv.transform(["hello comment my name is goving"]).toarray()

array([[0, 1, 0, 0, 0]])

<h4>N-grams</h4>

In [39]:
from nltk.util import ngrams
from nltk.tokenize import word_tokenize

text="I love natural language processing"
token=word_tokenize(text)
n=3

trigrams=list(ngrams(token,n))
print("trigrams:",trigrams)

trigrams: [('I', 'love', 'natural'), ('love', 'natural', 'language'), ('natural', 'language', 'processing')]


<h4> TF-IDF</h4>

In [40]:
from sklearn.feature_extraction.text import TfidfVectorizer
text=["i love natural language processing",
       "i love machine learning",
       "i love deep learning",]
vectorizer=TfidfVectorizer()
tfidf_matrix=vectorizer.fit_transform(text)

feature_names=vectorizer.get_feature_names_out()

for doc_index, doc in enumerate(tfidf_matrix.toarray()):
    print("Document=>",doc_index + 1)
    for word_index, score in enumerate(doc):
        if score > 0:
            print(f"{feature_names[word_index]}: {score:.4f}")

Document=> 1
language: 0.5465
love: 0.3227
natural: 0.5465
processing: 0.5465
Document=> 2
learning: 0.5478
love: 0.4254
machine: 0.7203
Document=> 3
deep: 0.7203
learning: 0.5478
love: 0.4254


In [41]:
vectorizer.get_feature_names_out()

array(['deep', 'language', 'learning', 'love', 'machine', 'natural',
       'processing'], dtype=object)

<h4>Part of speech tagging</h4>

In [42]:
import spacy

In [43]:
pos=spacy.load("en_core_web_sm")

In [44]:
doc=pos("I love natural language processing")

In [45]:
doc.text

'I love natural language processing'

In [46]:
doc[3].pos_

'NOUN'

In [47]:
doc[0].pos_

'PRON'

In [48]:
from nltk.stem import PorterStemmer
st=PorterStemmer()
print(st.stem("loving"))

love


In [49]:
print(st.stem("loving"))
st.stem("loving")

love


'love'