In [1]:
import tensorflow as tf
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv('credit .csv')

In [3]:
df.duplicated().sum()

np.int64(1)

In [4]:
df.drop_duplicates(inplace=True)

In [5]:
df.duplicated().sum()

np.int64(0)

In [6]:
df.isnull().sum()

age          2
job          6
marital      3
education    4
balance      0
housing      3
duration     2
campaign     0
approval     0
dtype: int64

In [7]:
df.dropna(inplace=True)

In [8]:
df.isnull().sum()

age          0
job          0
marital      0
education    0
balance      0
housing      0
duration     0
campaign     0
approval     0
dtype: int64

In [9]:
df.dtypes

age          float64
job           object
marital       object
education     object
balance        int64
housing       object
duration     float64
campaign       int64
approval      object
dtype: object

In [10]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
le=LabelEncoder()
df['job']=le.fit_transform(df['job'])

In [11]:
df['education']=le.fit_transform(df['education'])

In [12]:
df['marital']=le.fit_transform(df['marital'])

In [13]:
df['marital'].unique()

array([1, 2, 0])

In [14]:
# ohe=OneHotEncoder()
# df[['approval']]=ohe.fit_transform(df[['approval']])

In [15]:
df

,age,job,marital,education,balance,housing,duration,campaign,approval
0,30.0,10,1,0,1787,no,79.0,1,no
1,33.0,7,1,1,4789,yes,220.0,1,no
2,35.0,4,2,2,1350,yes,185.0,1,no
3,30.0,4,1,2,1476,yes,199.0,4,no
4,59.0,1,1,1,0,yes,226.0,1,no
...,...,...,...,...,...,...,...,...,...
4516,99.0,7,1,1,-333,yes,329.0,5,no
4517,57.0,6,1,2,-3313,yes,-153.0,1,no
4518,57.0,9,1,1,295,no,151.0,11,no
4519,28.0,1,1,1,1137,no,129.0,4,no


In [16]:
df.dtypes

age          float64
job            int64
marital        int64
education      int64
balance        int64
housing       object
duration     float64
campaign       int64
approval      object
dtype: object

In [17]:
df['approval'].unique()

array(['no', 'yes'], dtype=object)

In [18]:
df['housing']=df['housing'].map({'yes':1, 'no':0})

In [19]:
df['approval']=df['approval'].map({'yes':1, 'no':0})

In [20]:
df

,age,job,marital,education,balance,housing,duration,campaign,approval
0,30.0,10,1,0,1787,0,79.0,1,0
1,33.0,7,1,1,4789,1,220.0,1,0
2,35.0,4,2,2,1350,1,185.0,1,0
3,30.0,4,1,2,1476,1,199.0,4,0
4,59.0,1,1,1,0,1,226.0,1,0
...,...,...,...,...,...,...,...,...,...
4516,99.0,7,1,1,-333,1,329.0,5,0
4517,57.0,6,1,2,-3313,1,-153.0,1,0
4518,57.0,9,1,1,295,0,151.0,11,0
4519,28.0,1,1,1,1137,0,129.0,4,0


In [21]:
df.to_csv('credit_cleaned.csv')

In [22]:
df=pd.read_csv('credit_cleaned.csv')

In [23]:
x=df.drop('approval',axis=1)
y=df['approval']

In [24]:
x

,Unnamed: 0,age,job,marital,education,balance,housing,duration,campaign
0,0,30.0,10,1,0,1787,0,79.0,1
1,1,33.0,7,1,1,4789,1,220.0,1
2,2,35.0,4,2,2,1350,1,185.0,1
3,3,30.0,4,1,2,1476,1,199.0,4
4,4,59.0,1,1,1,0,1,226.0,1
...,...,...,...,...,...,...,...,...,...
4495,4516,99.0,7,1,1,-333,1,329.0,5
4496,4517,57.0,6,1,2,-3313,1,-153.0,1
4497,4518,57.0,9,1,1,295,0,151.0,11
4498,4519,28.0,1,1,1,1137,0,129.0,4


In [25]:
y

0       0
1       0
2       0
3       0
4       0
       ..
4495    0
4496    0
4497    0
4498    0
4499    0
Name: approval, Length: 4500, dtype: int64

In [26]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [27]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [28]:
input_shape = x_train.shape[1]
input_shape

9

In [29]:
model=Sequential()
model.add(Dense(units=128, activation='relu', input_dim=(input_shape)))
model.add(Dense(units=64, activation='relu'))
model.add(Dense(units=32, activation='relu'))
model.add(Dense(units=16, activation='relu'))
model.add(Dense(units=8, activation='relu'))

model.add(Dense(units=1, activation='sigmoid'))

model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

c:\Users\disha\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\layers\core\dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [30]:
model.fit(x_train, y_train, epochs=10, batch_size=32)

Epoch 1/10
113/113 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8640 - loss: 1.3908
Epoch 2/10
113/113 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8976 - loss: 0.4363
Epoch 3/10
113/113 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8880 - loss: 0.3783
Epoch 4/10
113/113 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8782 - loss: 0.3892
Epoch 5/10
113/113 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8880 - loss: 0.3766
Epoch 6/10
113/113 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8927 - loss: 0.3512
Epoch 7/10
113/113 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8890 - loss: 0.3529
Epoch 8/10
113/113 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8733 - loss: 0.3850
Epoch 9/10
113/113 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8857 - loss: 0.3579
Epoch 10/10
113/113 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8859 - loss: 0.3365


In [31]:
pred=model.predict(x_test)

29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step


In [34]:
pred=np.ravel(pred)

In [35]:
pred

array([3.10117304e-01, 6.13224991e-02, 1.34186158e-02, 1.80584088e-01,
       7.69539028e-02, 1.19665220e-01, 3.49643469e-01, 3.03004503e-01,
       3.10359932e-02, 1.24885716e-01, 2.84329712e-01, 6.57581538e-02,
       5.70827797e-02, 8.25133249e-02, 1.11490749e-01, 1.87786650e-02,
       1.70761436e-01, 1.01846159e-02, 2.75939733e-01, 3.49643469e-01,
       4.07462753e-02, 1.15748674e-01, 1.15042321e-01, 1.85286310e-02,
       1.26623670e-02, 1.58953547e-01, 3.49643469e-01, 2.56785750e-01,
       3.49643469e-01, 1.57807574e-01, 1.67000033e-02, 1.06394470e-01,
       2.26341397e-01, 9.13998857e-03, 7.15336064e-03, 1.45096602e-02,
       1.14151068e-01, 9.57537591e-02, 1.76042542e-02, 1.65768769e-02,
       3.49643469e-01, 1.57827914e-01, 3.05836260e-01, 1.91500470e-01,
       2.64718443e-01, 1.91045314e-01, 6.80079907e-02, 2.35660523e-02,
       3.48082721e-01, 2.38502681e-01, 5.57109416e-02, 9.63525549e-02,
       1.12601094e-01, 5.47784474e-03, 4.48403470e-02, 3.49643469e-01,
      

In [36]:
y_test

2323    1
3686    0
2974    1
2992    1
468     1
       ..
911     0
809     0
2940    1
3710    0
3257    0
Name: approval, Length: 900, dtype: int64

In [37]:
output=pd.DataFrame({'Actual': y_test, 'Prediction':(pred>=0.5).astype(int)})

In [38]:
output

,Actual,Prediction
2323,1,0
3686,0,0
2974,1,0
2992,1,0
468,1,0
...,...,...
911,0,0
809,0,0
2940,1,0
3710,0,0


In [39]:
loss, accuracy = model.evaluate(x_test, y_test)
print(f'Test Accuracy: {accuracy:.4f}')


29/29 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8825 - loss: 0.3722
Test Accuracy: 0.8878


In [ ]:
from sklearn.metrics import classification_report, confusion_matrix
print(classification_report(y_test, (pred>=0.5).astype(int)))
print(confusion_matrix(y_test, (pred>=0.5).astype(int))) 

#this will show how well the model is performing on the test data


              precision    recall  f1-score   support

           0       0.89      1.00      0.94       799
           1       0.00      0.00      0.00       101

    accuracy                           0.89       900
   macro avg       0.44      0.50      0.47       900
weighted avg       0.79      0.89      0.84       900

[[799   0]
 [101   0]]


c:\Users\disha\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1706: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\disha\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1706: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\disha\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1706: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(ave